# Generated by Django 2.0.4 on 2018-06-10 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portal.Persona')),
                ('ocupacion', models.CharField(blank=True, max_length=100)),
                ('estado_civil', models.CharField(choices=[('SO', 'Soltero/a'), ('C', 'Casado/a'), ('V', 'Viudo/a'), ('D', 'Divorciado/a'), ('SE', 'Separado/a')], max_length=2)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
                ('telefono_celular', models.CharField(blank=True, max_length=13, null=True)),
                ('telefono_domiclio', models.CharField(blank=True, max_length=13, null=True)),
            ],
            bases=('portal.persona',),
        ),
        migrations.RemoveField(
            model_name='pariente',
            name='persona_ptr',
        ),
        migrations.RemoveField(
            model_name='pariente',
            name='usuario_login',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='usuario_login',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='parientes',
        ),
        migrations.DeleteModel(
            name='Pariente',
        ),
        migrations.AddField(
            model_name='paciente',
            name='supervisor_asignado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Supervisor'),
        ),
    ]
