# Generated by Django 2.0.4 on 2018-06-17 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portal.Persona')),
                ('email', models.EmailField(max_length=120)),
                ('telefono_celular', models.CharField(blank=True, max_length=13, null=True)),
                ('telefono_domiclio', models.CharField(blank=True, max_length=13, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('portal.persona',),
        ),
    ]
