# Generated by Django 2.0.4 on 2018-06-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credenciales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('permisos', models.CharField(choices=[('M', 'Medico'), ('P', 'Pariente')], max_length=1)),
            ],
        ),
    ]
