# Generated by Django 2.0.3 on 2018-05-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='estado_social',
            field=models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('D', 'Divorsiado'), ('O', 'Otro')], default=None, max_length=1),
            preserve_default=False,
        ),
    ]
