# Generated by Django 2.0.4 on 2018-05-30 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='peraciones',
            new_name='operaciones',
        ),
    ]
