# Generated by Django 2.0.4 on 2018-06-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0002_auto_20180530_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='ocupacion',
        ),
        migrations.AddField(
            model_name='pariente',
            name='estado_civil',
            field=models.CharField(choices=[('SO', 'Soltero/a'), ('C', 'Casado/a'), ('V', 'Viudo/a'), ('D', 'Divorciado/a'), ('SE', 'Separado/a')], default='SO', max_length=2),
        ),
        migrations.AddField(
            model_name='pariente',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
