# Generated by Django 2.0.4 on 2018-06-05 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0002_auto_20180605_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='usuario_login',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Credenciales'),
        ),
    ]
