# Generated by Django 2.0.3 on 2018-05-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0005_auto_20180511_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='rut',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
